[project]
name = "airbnb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=3.3.2",
    "boto3>=1.43.108",
    "dbt-core>=1.12.5",
    "dbt-postgres>=1.11.0",
    "psycopg2>=2.9.13",
    "python-dotenv>=1.2.4",
]

[dependency-groups]
dev = [
    "astronomer-cosmos>=1.15.1",
]
